version: "3"

services:
  api:
    container_name: "go-there-api"
    build:
      context: .
      dockerfile: .devcontainer/containers/api/Dockerfile
    volumes:
      - ./:/go/src
    ports:
      - 80:8080
    # command:
    #   ["air", "-c", ".air.toml"]
    tty:
      true
